apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitcode-interceptor-listener
  labels:
    app: gitcode-interceptor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitcode-interceptor
  template:
    metadata:
      labels:
        app: gitcode-interceptor
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: tekton-triggers-sa # 使用 triggers 的 sa 获取权限
      containers:
        - name: listener
          image: pkking/gitcode-tekton-interceptor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: gitcode-interceptor-service
spec:
  selector:
    app: gitcode-interceptor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterInterceptor
metadata:
  # 这个 name ("gitcode") 必须和 main.go 中注册的 key 一致
  name: gitcode
spec:
  clientConfig:
    service:
      name: gitcode-interceptor-service
      namespace: default
      port: 80