apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitee-interceptor-listener
  namespace: tekton-pipelines # 推荐与 Tekton 组件在同一个命名空间
  labels:
    app: gitee-interceptor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitee-interceptor
  template:
    metadata:
      labels:
        app: gitee-interceptor
    spec:
      serviceAccountName: tekton-triggers-sa # 使用 triggers 的 sa 获取权限
      containers:
        - name: listener
          image: lcrpkking/gitee-tekton-interceptor:v0.1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gitee-interceptor-service
  namespace: tekton-pipelines
spec:
  selector:
    app: gitee-interceptor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterInterceptor
metadata:
  # 这个 name ("gitee") 必须和 main.go 中注册的 key 一致
  name: gitee
spec:
  clientConfig:
    # URL 指向我们创建的 Service
    url:
      - http://gitee-interceptor-service.tekton-pipelines.svc.cluster.local
