# deploy/task.yaml (CORRECTED)
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-repo-script
spec:
  description: >-
    This task clones a repository, checks out a specific revision,
    and runs a custom script from within that repo.
  params:
    - name: repoUrl
      description: The git repository URL to clone from.
    - name: revision
      description: The git revision to check out.
  workspaces:
    - name: source
      description: A workspace for the cloned repository.
  steps:
    - name: run-the-script
      image: pkking/task:latest
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        ls -la **
        id
        if [ ! -f "scripts/run.sh" ]; then
          echo "Error: scripts/run.sh not found!"
          exit 1
        fi
        
        chmod +x scripts/run.sh
        ./scripts/run.sh